# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: batch6

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.600'
  targetRuntime: 'linux-x64'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
  
    - script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
      displayName: Publish Project 
  
    - task: Npm@1
      displayName: Test UI
      inputs:
        command: 'custom'
        workingDir: 'ClientApp'
        customCommand: 'run test --watch=false'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


    # - task: DotNetCoreCLI@2
    #   displayName: Publish Projects
    #   inputs:
    #     command: 'publish'
    #     publishWebProjects: true
    #     arguments: '--configuration $(buildConfiguration) -f $(dotNetFramework) --runtime $(targetRuntime) --self-contained -o $(Build.ArtifactStagingDirectory)'
    #     zipAfterPublish: true
  
      # Test project
    # - script: dotnet test
    #   displayName: Test Project